name: NoSleepDebuff
version: '${project.version}'
main: me.valdoveste.nosleepdebuff.NoSleepDebuff
api-version: 1.19
authors: [ Valdoveste ]
commands:
  nosleepreload:
    description: Este comando dรก reload no "config.yml" do plugin.
    usage: /<command>